const scoringDefault={passYds:.04,passTD:4,INT:-2,rushYds:.1,rushTD:6,rec:.1,recYds:.1,recTD:6,fumble:-2};
let scoring=JSON.parse(localStorage.getItem('ffm_scoring')||'null')||{...scoringDefault};
let state={mode:localStorage.getItem('ffm_mode')||'PPR',teams:+(localStorage.getItem('ffm_teams')||12),pos:'ALL',sort:'rank',search:''};
let data=null, players=[];
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('ffm_mode',state.mode);localStorage.setItem('ffm_teams',state.teams);localStorage.setItem('ffm_scoring',JSON.stringify(scoring));}
function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}
function projection(p){return state.mode==='PPR'?{proj:p.projectionPPR,ppg:p.ppgPPR,floor:p.floorPPR,ceiling:p.ceilingPPR,rank:p.modelRankPPR}:{proj:p.projectionNonPPR,ppg:p.ppgNonPPR,floor:p.floorNonPPR,ceiling:p.ceilingNonPPR,rank:p.modelRankNonPPR};}
function render(){
 let a=players.filter(p=>(state.pos==='ALL'||p.position===state.pos)&&p.name.toLowerCase().includes(state.search.toLowerCase()));
 a.sort((x,y)=>{if(state.sort==='name')return x.name.localeCompare(y.name);if(state.sort==='pos')return x.position.localeCompare(y.position)||projection(x).rank-projection(y).rank;return projection(x).rank-projection(y).rank;});
 $('players').innerHTML=a.length?a.map(p=>{const q=projection(p);return `<article class="player" onclick="detail('${esc(p.playerId)}')"><div class="phead"><div><div class="name">${esc(p.name)}</div><div class="pos"><span class="tag">${esc(p.position)}</span> ${esc(p.team||'')}</div></div><div class="rank">#${q.rank}</div></div><div class="stats"><div class="stat"><div class="label">Projection</div><div class="value">${q.proj.toFixed(1)}</div></div><div class="stat"><div class="label">PPG</div><div class="value">${q.ppg.toFixed(2)}</div></div><div class="stat"><div class="label">Floor</div><div class="value">${q.floor.toFixed(1)}</div></div><div class="stat"><div class="label">Ceiling</div><div class="value">${q.ceiling.toFixed(1)}</div></div></div></article>`}).join(''):'<div class="empty">No model projections match those filters.</div>';
 $('status').textContent=data?`V${data.modelVersion} • ${data.players.length} modeled players • source: ${data.source}`:'Model data is still being generated.';
}
function detail(id){const p=players.find(x=>x.playerId===id);if(!p)return;const q=projection(p);document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const d=$('detail');d.classList.add('active');d.innerHTML=`<div class="detailback"><button class="btn secondary" onclick="go('rankings')">← Rankings</button></div><div class="hero"><h2>${esc(p.name)}</h2><p>${esc(p.position)} • ${esc(p.team||'')} • Model rank #${q.rank}</p></div><div class="panel"><div class="detailgrid"><div class="detailbox"><div class="label">Season projection</div><div class="big">${q.proj.toFixed(1)}</div></div><div class="detailbox"><div class="label">PPG</div><div class="big">${q.ppg.toFixed(2)}</div></div><div class="detailbox"><div class="label">Floor</div><div class="big">${q.floor.toFixed(1)}</div></div><div class="detailbox"><div class="label">Ceiling</div><div class="big">${q.ceiling.toFixed(1)}</div></div></div></div><div class="panel"><div class="row"><b>ADP</b><span class="small">Not connected yet</span></div><div class="row"><b>Draft value</b><span class="small">Requires ESPN/Sleeper ADP</span></div><div class="row"><b>Health assumption</b><span class="small">Healthy/available; injury probability is not modeled</span></div><div class="row"><b>Model</b><span class="small">V${esc(data.modelVersion)} • ${esc(data.source)} historical data</span></div></div>`;window.scrollTo(0,0);}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo(0,0);}
function setMode(){ $('ppr').classList.toggle('active',state.mode==='PPR');$('nonppr').classList.toggle('active',state.mode==='Non-PPR');$('scoringLabel').textContent=state.mode;save();render();}
function renderScoring(){const labels={passYds:'Passing yards / point',passTD:'Passing TD',INT:'Interception',rushYds:'Rushing yards / point',rushTD:'Rushing TD',rec:'Reception',recYds:'Receiving yards / point',recTD:'Receiving TD',fumble:'Fumble lost'};$('scoring').innerHTML=Object.entries(scoring).map(([k,v])=>`<div class="row"><span>${labels[k]||k}</span><input data-score="${k}" type="number" step="0.01" value="${v}" style="width:90px;padding:7px;border:1px solid #ddd;border-radius:8px"></div>`).join('');document.querySelectorAll('[data-score]').forEach(i=>i.onchange=()=>{scoring[i.dataset.score]=+i.value;save();});}
async function load(){try{const r=await fetch('data/projections.json?'+Date.now());if(!r.ok)throw Error('not ready');data=await r.json();players=data.players||[];$('notice').innerHTML=`<b>Real model data loaded.</b> V${data.modelVersion} generated from ${data.source} historical data. 2026 projections assume healthy/available players; injury probability and betting markets are not used.`;$('methodText').innerHTML=`<div class="row"><b>Data</b><span class="small">nflverse player statistics, 2012–2025</span></div><div class="row"><b>Target</b><span class="small">Next-season fantasy PPG, trained using forward-in-time season transitions</span></div><div class="row"><b>Development</b><span class="small">Age/experience plus recent and three-year production trends</span></div><div class="row"><b>Environment</b><span class="small">Team passing/rushing volume and scoring context</span></div><div class="row"><b>TD regression</b><span class="small">TD rate is included as a predictive feature rather than manually regressed</span></div><div class="row"><b>Uncertainty</b><span class="small">Quantile models generate the 10th/50th/90th percentile outcome range</span></div><div class="row"><b>Validation</b><span class="small">${(data.validation||[]).map(v=>`${v.position}: ${v.mae_ppg} PPG MAE`).join(' • ')}</span></div>`;render();}catch(e){$('notice').innerHTML='<b>Model build in progress.</b> The app will switch to real projections automatically after the GitHub model workflow finishes.';render();}}
function wire(){document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$('ppr').onclick=()=>{state.mode='PPR';setMode()};$('nonppr').onclick=()=>{state.mode='Non-PPR';setMode()};$('search').oninput=e=>{state.search=e.target.value;render()};$('pos').onchange=e=>{state.pos=e.target.value;render()};$('sort').onchange=e=>{state.sort=e.target.value;render()};$('teams').onchange=e=>{state.teams=+e.target.value;save()};$('update').onclick=async()=>{await load();$('updateMsg').textContent='Reloaded the latest generated model data.'};$('reset').onclick=()=>{state.teams=12;state.mode='PPR';scoring={...scoringDefault};save();$('teams').value=12;setMode();renderScoring();};}
wire();$('teams').value=state.teams;setMode();renderScoring();load();
